import 'dart:async';
import 'dart:convert';
import 'dart:ffi';
import 'dart:io';
import 'dart:isolate';
import 'dart:ui';

import 'package:ffi/ffi.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:test_api/backend.dart';
import 'package:stream_channel/stream_channel.dart';
import 'package:stream_channel/isolate_channel.dart';
import 'package:stack_trace/stack_trace.dart';
import 'package:test_core/src/executable.dart' as test; // ignore: implementation_imports
import 'package:test_core/src/platform.dart';  // ignore: implementation_imports

import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/dynamic_intrinsics_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_dynamic_intrinsics_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/flutter_test_config.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/debug_overflow_indicator_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_debug_overflow_indicator_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/view_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_view_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/binding_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_binding_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/platform_view_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_platform_view_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/positioned_box_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_positioned_box_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/repaint_boundary_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_repaint_boundary_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/reattach_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_reattach_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/sliver_persistent_header_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_sliver_persistent_header_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/limited_box_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_limited_box_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/memory_allocations_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_memory_allocations_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/pipeline_owner_tree_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_pipeline_owner_tree_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/table_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_table_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/relative_rect_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_relative_rect_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/viewport_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_viewport_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/constraints_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_constraints_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/paint_error_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_paint_error_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/flex_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_flex_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/repaint_boundary_2_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_repaint_boundary_2_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/mutations_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_mutations_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/size_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_size_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/selection_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_selection_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/offstage_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_offstage_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/transform_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_transform_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/slivers_layout_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_slivers_layout_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/painting_context_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_painting_context_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/box_constraints_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_box_constraints_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/object_paint_dispose_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_object_paint_dispose_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/paragraph_intrinsics_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_paragraph_intrinsics_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/proxy_box_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_proxy_box_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/slivers_helpers_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_slivers_helpers_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/editable_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_editable_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/flex_overflow_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_flex_overflow_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/binding_pipeline_manifold_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_binding_pipeline_manifold_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/proxy_getters_and_setters_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_proxy_getters_and_setters_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/image_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_image_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/annotated_region_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_annotated_region_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/editable_gesture_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_editable_gesture_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/paragraph_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_paragraph_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/error_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_error_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/wrap_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_wrap_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/independent_layout_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_independent_layout_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/object_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_object_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/layer_annotations_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_layer_annotations_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/simple_semantics_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_simple_semantics_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/proxy_sliver_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_proxy_sliver_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/stack_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_stack_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/sliver_cache_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_sliver_cache_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/mouse_tracker_cursor_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_mouse_tracker_cursor_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/slivers_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_slivers_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/aspect_ratio_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_aspect_ratio_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/non_normalized_constraints_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_non_normalized_constraints_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/view_chrome_style_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_view_chrome_style_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/baseline_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_baseline_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/intrinsic_width_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_intrinsic_width_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/multi_view_binding_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_multi_view_binding_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/mouse_tracker_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_mouse_tracker_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/relayout_boundary_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_relayout_boundary_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/binding_pipeline_manifold_init_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_binding_pipeline_manifold_init_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/sliver_fixed_extent_layout_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_sliver_fixed_extent_layout_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/debug_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_debug_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/box_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_box_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/localized_fonts_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_localized_fonts_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/first_frame_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_first_frame_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/slivers_block_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_slivers_block_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/table_border_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_table_border_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/overflow_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_overflow_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/layers_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_layers_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/cached_intrinsics_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_cached_intrinsics_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/semantics_and_children_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_semantics_and_children_test;
import 'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/viewport_caching_test.dart' as _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_viewport_caching_test;

const List<String> testPaths = <String>[
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/dynamic_intrinsics_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/debug_overflow_indicator_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/view_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/binding_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/platform_view_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/positioned_box_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/repaint_boundary_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/reattach_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/sliver_persistent_header_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/limited_box_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/memory_allocations_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/pipeline_owner_tree_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/table_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/relative_rect_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/viewport_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/constraints_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/paint_error_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/flex_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/repaint_boundary_2_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/mutations_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/size_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/selection_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/offstage_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/transform_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/slivers_layout_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/painting_context_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/box_constraints_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/object_paint_dispose_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/paragraph_intrinsics_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/proxy_box_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/slivers_helpers_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/editable_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/flex_overflow_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/binding_pipeline_manifold_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/proxy_getters_and_setters_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/image_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/annotated_region_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/editable_gesture_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/paragraph_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/error_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/wrap_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/independent_layout_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/object_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/layer_annotations_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/simple_semantics_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/proxy_sliver_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/stack_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/sliver_cache_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/mouse_tracker_cursor_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/slivers_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/aspect_ratio_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/non_normalized_constraints_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/view_chrome_style_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/baseline_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/intrinsic_width_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/multi_view_binding_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/mouse_tracker_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/relayout_boundary_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/binding_pipeline_manifold_init_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/sliver_fixed_extent_layout_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/debug_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/box_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/localized_fonts_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/first_frame_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/slivers_block_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/table_border_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/overflow_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/layers_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/cached_intrinsics_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/semantics_and_children_test.dart',
  'file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/viewport_caching_test.dart',
];
@Native<Void Function(Pointer<Utf8>, Pointer<Utf8>)>(symbol: 'Spawn')
external void _spawn(Pointer<Utf8> entrypoint, Pointer<Utf8> route);

void spawn({required SendPort port, String entrypoint = 'main', String route = '/'}) {
  // Get off the UI isolate, otherwise there will be a current isolate that
  // cannot safely be exited.
  Isolate.run(() {
    assert(
      entrypoint != 'main' || route != '/',
      'Spawn should not be used to spawn main with the default route name',
    );
    IsolateNameServer.registerPortWithName(port, route);
    _spawn(entrypoint.toNativeUtf8(), route.toNativeUtf8());
  });
}

/// Runs on a spawned isolate.
void createChannelAndConnect(String path, String name, Function testMain) {
  goldenFileComparator = LocalFileComparator(Uri.parse(path));
  autoUpdateGoldenFiles = false;
  final channel = IsolateChannel.connectSend(IsolateNameServer.lookupPortByName(name)!);
  channel.pipe(RemoteListener.start(() => testMain));
}

/// Runs on the main isolate.
void registerPluginAndRun() {
  final platform = SpawnPlugin(testPaths);
  registerPlatformPlugin(
    <Runtime>[Runtime.vm],
    () { return platform; },
  );
  test.main(<String>['--', ...testPaths]);
}

void main() {
  final String route = PlatformDispatcher.instance.defaultRouteName;
  switch (route) {
    case '/': registerPluginAndRun();

    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_dynamic_intrinsics_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/dynamic_intrinsics_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_dynamic_intrinsics_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_debug_overflow_indicator_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/debug_overflow_indicator_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_debug_overflow_indicator_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_view_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/view_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_view_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_binding_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/binding_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_binding_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_platform_view_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/platform_view_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_platform_view_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_positioned_box_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/positioned_box_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_positioned_box_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_repaint_boundary_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/repaint_boundary_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_repaint_boundary_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_reattach_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/reattach_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_reattach_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_sliver_persistent_header_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/sliver_persistent_header_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_sliver_persistent_header_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_limited_box_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/limited_box_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_limited_box_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_memory_allocations_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/memory_allocations_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_memory_allocations_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_pipeline_owner_tree_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/pipeline_owner_tree_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_pipeline_owner_tree_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_table_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/table_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_table_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_relative_rect_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/relative_rect_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_relative_rect_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_viewport_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/viewport_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_viewport_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_constraints_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/constraints_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_constraints_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_paint_error_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/paint_error_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_paint_error_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_flex_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/flex_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_flex_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_repaint_boundary_2_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/repaint_boundary_2_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_repaint_boundary_2_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_mutations_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/mutations_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_mutations_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_size_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/size_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_size_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_selection_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/selection_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_selection_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_offstage_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/offstage_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_offstage_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_transform_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/transform_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_transform_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_slivers_layout_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/slivers_layout_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_slivers_layout_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_painting_context_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/painting_context_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_painting_context_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_box_constraints_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/box_constraints_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_box_constraints_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_object_paint_dispose_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/object_paint_dispose_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_object_paint_dispose_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_paragraph_intrinsics_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/paragraph_intrinsics_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_paragraph_intrinsics_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_proxy_box_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/proxy_box_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_proxy_box_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_slivers_helpers_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/slivers_helpers_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_slivers_helpers_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_editable_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/editable_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_editable_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_flex_overflow_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/flex_overflow_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_flex_overflow_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_binding_pipeline_manifold_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/binding_pipeline_manifold_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_binding_pipeline_manifold_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_proxy_getters_and_setters_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/proxy_getters_and_setters_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_proxy_getters_and_setters_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_image_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/image_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_image_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_annotated_region_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/annotated_region_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_annotated_region_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_editable_gesture_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/editable_gesture_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_editable_gesture_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_paragraph_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/paragraph_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_paragraph_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_error_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/error_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_error_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_wrap_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/wrap_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_wrap_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_independent_layout_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/independent_layout_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_independent_layout_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_object_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/object_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_object_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_layer_annotations_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/layer_annotations_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_layer_annotations_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_simple_semantics_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/simple_semantics_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_simple_semantics_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_proxy_sliver_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/proxy_sliver_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_proxy_sliver_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_stack_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/stack_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_stack_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_sliver_cache_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/sliver_cache_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_sliver_cache_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_mouse_tracker_cursor_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/mouse_tracker_cursor_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_mouse_tracker_cursor_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_slivers_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/slivers_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_slivers_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_aspect_ratio_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/aspect_ratio_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_aspect_ratio_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_non_normalized_constraints_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/non_normalized_constraints_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_non_normalized_constraints_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_view_chrome_style_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/view_chrome_style_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_view_chrome_style_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_baseline_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/baseline_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_baseline_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_intrinsic_width_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/intrinsic_width_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_intrinsic_width_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_multi_view_binding_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/multi_view_binding_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_multi_view_binding_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_mouse_tracker_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/mouse_tracker_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_mouse_tracker_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_relayout_boundary_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/relayout_boundary_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_relayout_boundary_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_binding_pipeline_manifold_init_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/binding_pipeline_manifold_init_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_binding_pipeline_manifold_init_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_sliver_fixed_extent_layout_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/sliver_fixed_extent_layout_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_sliver_fixed_extent_layout_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_debug_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/debug_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_debug_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_box_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/box_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_box_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_localized_fonts_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/localized_fonts_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_localized_fonts_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_first_frame_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/first_frame_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_first_frame_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_slivers_block_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/slivers_block_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_slivers_block_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_table_border_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/table_border_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_table_border_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_overflow_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/overflow_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_overflow_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_layers_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/layers_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_layers_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_cached_intrinsics_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/cached_intrinsics_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_cached_intrinsics_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_semantics_and_children_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/semantics_and_children_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_semantics_and_children_test.main));
    case '_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_viewport_caching_test': createChannelAndConnect('file:///home/runner/work/flutter_test_ci/flutter_test_ci/flutter/packages/flutter/test/rendering/viewport_caching_test.dart', route, () => _home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_flutter_test_config.testExecutable(_home_runner_work_flutter_test_ci_flutter_test_ci_flutter_packages_flutter_test_rendering_viewport_caching_test.main));
  }
}

String pathToImport(String path) {
  assert(path.endsWith('.dart'));
  return path
      .replaceRange(path.length - '.dart'.length, null, '')
      .replaceFirst('file://', '')
      .replaceAll('.', '_')
      .replaceAll('/', '_')
      .replaceAll(r'\', '_');
}

class SpawnPlugin extends PlatformPlugin {
  SpawnPlugin(List<String> testPaths) {
    for (final String path in testPaths) {
      final String name = pathToImport(path);
      ReceivePort port = ReceivePort();
      _channels[name] = IsolateChannel.connectReceive(port);
      spawn(port: port.sendPort, route: name);
    }
  }

  final Map<String, IsolateChannel> _channels = {};

  @override
  Future<RunnerSuite> load(
    String path,
    SuitePlatform platform,
    SuiteConfiguration suiteConfig,
    Object message,
  ) async {
    final StreamChannel<dynamic> channel = _channels[pathToImport(path)]!;
    final RunnerSuiteController controller = deserializeSuite(path, platform,
      suiteConfig, const PluginEnvironment(), channel, message);
    return controller.suite;
  }
}

