name: Regular Flutter Test
on: [push]
jobs:
  ft:
    runs-on: ubuntu-latest
    steps:
      - run: echo $PWD
      - run: git clone --depth=1 https://github.com/dnfield/flutter_test_ci .
      - run: git clone https://github.com/flutter/flutter && git -C flutter reset --hard 961f955af2b139e31117d963e8c533912e2cc0b9
      - run: echo "$PWD/flutter/bin" >> $GITHUB_PATH
      - run: flutter pub get
      - run: flutter/bin/dart --disable-dart-dev $PWD/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --packages $PWD/.dart_tool/package_config.json --sdk-root $PWD/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk --target flutter --output-dill $PWD/mega_test.dart.dill $PWD/mega_test.dart
      - run: FLUTTER_ROOT=$PWD/flutter FLUTTER_TEST=true $PWD/flutter_tester --disable-observatory --use-test-fonts --disable-asset-fonts --flutter-assets-dir=$PWD --icu-data-file-path=$PWD/icudtl.dat $PWD/mega_test.dart.dill
